/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import ifsc.poo.listaUm.*;
import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        if (args.length == 0) return;
        byte nExercicio = Byte.parseByte(args[0]);
        args =  Arrays.copyOfRange(args, 1, args.length);
        switch (nExercicio) {
            case 1 -> Exercicio1.main(args);
            case 2 -> Exercicio2.main(args);
            case 3 -> Exercicio3.main(args);
            case 4 -> Exercicio4.main(args);
            case 5 -> Exercicio5.main(args);
            case 6 -> Exercicio6.main(args);
            case 7 -> Exercicio7.main(args);
            case 8 -> Exercicio8.main(args);
            case 9 -> Exercicio9.main(args);
            case 10 -> Exercicio10.main(args);
        }
    }
}
